-- MySQL Script generated by MySQL Workbench
-- Thu Dec 28 09:07:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Controledefeito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Controledefeito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Controledefeito` DEFAULT CHARACTER SET utf8 ;
USE `Controledefeito` ;

-- -----------------------------------------------------
-- Table `Controledefeito`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Veiculo` (
  `VEICULO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NUMERO_ID` VARCHAR(6) NOT NULL,
  `LINHA_ID` VARCHAR(45) NOT NULL,
  `ANO_ID` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VEICULO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Defeito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Defeito` (
  `DEFEITO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NUMERO_ID` VARCHAR(45) NOT NULL,
  `TIPO_ID` ENUM('motor', 'borracharia', 'mecanica', 'lanternagem', 'arcondicionado') NOT NULL,
  PRIMARY KEY (`DEFEITO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Data` (
  `DATA_ID` DATETIME NOT NULL,
  `HORA_ID` DATETIME NOT NULL,
  `Defeito_DEFEITO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DATA_ID`),
  INDEX `fk_Data_Defeito1_idx` (`Defeito_DEFEITO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Defeito1`
    FOREIGN KEY (`Defeito_DEFEITO_ID`)
    REFERENCES `Controledefeito`.`Defeito` (`DEFEITO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Local` (
  `ENDEREÇO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOCAL_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ENDEREÇO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`defeito_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`defeito_veiculo` (
  `Defeito_DEFEITO_ID` INT UNSIGNED NOT NULL,
  `Veiculo_VEICULO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Defeito_DEFEITO_ID`, `Veiculo_VEICULO_ID`),
  INDEX `fk_Defeito_has_Veiculo_Veiculo1_idx` (`Veiculo_VEICULO_ID` ASC) VISIBLE,
  INDEX `fk_Defeito_has_Veiculo_Defeito_idx` (`Defeito_DEFEITO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Defeito_has_Veiculo_Defeito`
    FOREIGN KEY (`Defeito_DEFEITO_ID`)
    REFERENCES `Controledefeito`.`Defeito` (`DEFEITO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Defeito_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_VEICULO_ID`)
    REFERENCES `Controledefeito`.`Veiculo` (`VEICULO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Local_has_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Local_has_Veiculo` (
  `Local_ENDEREÇO_ID` INT UNSIGNED NOT NULL,
  `Veiculo_VEICULO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Local_ENDEREÇO_ID`, `Veiculo_VEICULO_ID`),
  INDEX `fk_Local_has_Veiculo_Veiculo1_idx` (`Veiculo_VEICULO_ID` ASC) VISIBLE,
  INDEX `fk_Local_has_Veiculo_Local1_idx` (`Local_ENDEREÇO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Local_has_Veiculo_Local1`
    FOREIGN KEY (`Local_ENDEREÇO_ID`)
    REFERENCES `Controledefeito`.`Local` (`ENDEREÇO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_VEICULO_ID`)
    REFERENCES `Controledefeito`.`Veiculo` (`VEICULO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Motorista` (
  `Motorista_ID` INT NOT NULL,
  `MATRICULA_ID` VARCHAR(10) NOT NULL,
  `NOME_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Motorista_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Local_has_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Local_has_Data` (
  `Local_ENDEREÇO_ID` INT UNSIGNED NOT NULL,
  `Data_DATA_ID` DATETIME NOT NULL,
  PRIMARY KEY (`Local_ENDEREÇO_ID`, `Data_DATA_ID`),
  INDEX `fk_Local_has_Data_Data1_idx` (`Data_DATA_ID` ASC) VISIBLE,
  INDEX `fk_Local_has_Data_Local1_idx` (`Local_ENDEREÇO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Local_has_Data_Local1`
    FOREIGN KEY (`Local_ENDEREÇO_ID`)
    REFERENCES `Controledefeito`.`Local` (`ENDEREÇO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local_has_Data_Data1`
    FOREIGN KEY (`Data_DATA_ID`)
    REFERENCES `Controledefeito`.`Data` (`DATA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Motorista_has_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Motorista_has_Veiculo` (
  `Motorista_Motorista_ID` INT NOT NULL,
  `Veiculo_VEICULO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Motorista_Motorista_ID`, `Veiculo_VEICULO_ID`),
  INDEX `fk_Motorista_has_Veiculo_Veiculo1_idx` (`Veiculo_VEICULO_ID` ASC) VISIBLE,
  INDEX `fk_Motorista_has_Veiculo_Motorista1_idx` (`Motorista_Motorista_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Motorista_has_Veiculo_Motorista1`
    FOREIGN KEY (`Motorista_Motorista_ID`)
    REFERENCES `Controledefeito`.`Motorista` (`Motorista_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_VEICULO_ID`)
    REFERENCES `Controledefeito`.`Veiculo` (`VEICULO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controledefeito`.`Motorista_has_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controledefeito`.`Motorista_has_Data` (
  `Motorista_Motorista_ID` INT NOT NULL,
  `Data_DATA_ID` DATETIME NOT NULL,
  PRIMARY KEY (`Motorista_Motorista_ID`, `Data_DATA_ID`),
  INDEX `fk_Motorista_has_Data_Data1_idx` (`Data_DATA_ID` ASC) VISIBLE,
  INDEX `fk_Motorista_has_Data_Motorista1_idx` (`Motorista_Motorista_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Motorista_has_Data_Motorista1`
    FOREIGN KEY (`Motorista_Motorista_ID`)
    REFERENCES `Controledefeito`.`Motorista` (`Motorista_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_has_Data_Data1`
    FOREIGN KEY (`Data_DATA_ID`)
    REFERENCES `Controledefeito`.`Data` (`DATA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
